# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 14:07
from __future__ import unicode_literals

from django.db import migrations, models
from django.core import serializers
from django.core.management.commands.loaddata import Command
import django.db.models.deletion


def load_data(apps, schema_editor):
    cmd = Command()
    cmd.verbosity = 0
    cmd.using = 'default'
    cmd.app_label = 'yandexmoney_notice'
    cmd.compression_formats = {None: (open, 'rb')}
    cmd.serialization_formats = serializers.get_public_serializer_formats()

    for label in ('notification_types', 'currencies'):
        for obj in serializers.deserialize('yaml', open(cmd.find_fixtures(label)[0][0], 'rb')):
            obj.save()


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Код валюты счета пользователя. Всегда 643 (рубль РФ согласно ISO 4217).')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=13, unique=True, verbose_name='Тип перевода')),
            ],
        ),
        migrations.CreateModel(
            name='YadTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.CharField(max_length=50, verbose_name='Идентификатор операции в истории счета получателя')),
                ('amount', models.FloatField(max_length=9, verbose_name='Сумма операции')),
                ('withdraw_amount', models.FloatField(blank=True, max_length=9, null=True, verbose_name='Сумма, которая списана со счета отправителя')),
                ('datetime_transfer', models.DateTimeField(verbose_name='Дата и время совершения перевода')),
                ('sender', models.BigIntegerField(blank=True, null=True, verbose_name='Номер счета отправителя')),
                ('codepro', models.BooleanField(verbose_name='Защита кодом протекции')),
                ('label', models.CharField(blank=True, max_length=64, null=True, verbose_name='Метка платежа')),
                ('test_notification', models.BooleanField(verbose_name='Тестовое уведомление')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='yandexmoney_notice.Currencies')),
                ('n_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='yandexmoney_notice.NotificationTypes')),
            ],
        ),
        migrations.RunPython(load_data, do_nothing),
    ]
