# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YadTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('p2p-incoming', 'Перевод из кошелька'), ('card-incoming', 'Перевод с карты')], max_length=32, verbose_name='Тип перевода')),
                ('currency', models.IntegerField(choices=[(643, 'Рубль РФ')], verbose_name='Код валюты счёта пользователя')),
                ('operation_id', models.CharField(max_length=50, verbose_name='Идентификатор операции в истории счета получателя')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма операции')),
                ('withdraw_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма, которая списана со счета отправителя')),
                ('datetime_transfer', models.DateTimeField(verbose_name='Дата и время совершения перевода')),
                ('sender', models.CharField(blank=True, max_length=32, null=True, verbose_name='Номер счета отправителя')),
                ('codepro', models.BooleanField(verbose_name='Защита кодом протекции')),
                ('label', models.CharField(blank=True, max_length=64, null=True, verbose_name='Метка платежа')),
                ('test_notification', models.BooleanField(verbose_name='Тестовое уведомление')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
        ),
    ]
